name: mirapy

channels:
    - astropy

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - nbsphinx
    - sphinx-autoapi
#    - sphinx-astropy
#   - pip:
#       - dependency_from_pip
